// AUTO-GENERATED by split_tiles.py — do not edit by hand.
// Each entry is a literal dynamic import so the bundler can code-split
// and only fetch a tile's data when it is actually requested.
export const TILE_LOADERS: Record<string, () => Promise<any>> = {
  '35E': () => import('./35E'),
  '36E': () => import('./36E'),
};
